# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0003_auto_20180519_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School_class',
            new_name='SchoolClass',
        ),
    ]
