# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-19 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0004_auto_20180519_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': 'School classes'},
        ),
    ]
