# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0005_auto_20180519_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='students',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kosme.Teacher'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kosme.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='schoolClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kosme.SchoolClass'),
        ),
    ]
