# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-19 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0006_auto_20180519_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={},
        ),
        migrations.AddField(
            model_name='lecture',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
