# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0008_auto_20180521_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('data', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
