# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0009_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='data',
            field=models.TextField(max_length=1000),
        ),
    ]
