# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0009_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='courses',
            field=models.ManyToManyField(null=True, to='kosme.Course'),
        ),
    ]
