# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0011_auto_20180526_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosme.Student')),
            ],
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 26, 19, 52, 49, 251335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='courses',
            field=models.ManyToManyField(to='kosme.Course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='results',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kosme.Result'),
        ),
    ]
