# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0012_auto_20180526_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(to='kosme.SchoolClass'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 26, 20, 11, 57, 136883, tzinfo=utc)),
        ),
    ]
