# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 21:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0013_auto_20180526_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 26, 21, 39, 16, 79735, tzinfo=utc)),
        ),
    ]
