# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-27 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0014_auto_20180527_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kosme.Course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 8, 22, 11, 587749, tzinfo=utc)),
        ),
    ]
