# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-27 16:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0015_auto_20180527_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='results',
        ),
        migrations.AddField(
            model_name='result',
            name='quiz',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='kosme.Quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 16, 14, 51, 458319, tzinfo=utc)),
        ),
    ]
