# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-27 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0016_auto_20180527_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 16, 16, 32, 435597, tzinfo=utc)),
        ),
    ]
