# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-27 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kosme', '0017_auto_20180527_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 5, 27, 16, 19, 28, 578894, tzinfo=utc)),
        ),
    ]
